global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using NeMobileBg.Common;
global using NeMobileBg.Common.Models.Cars;
global using NeMobileBg.Common.Models.Home;
global using NeMobileBg.Common.Models.Motorcycles;
global using NeMobileBg.Data.Models;
global using NeMobileBg.Data.Repository;
global using NeMobileBg.Services.Contracts;
