// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeMobileBg.Data;

#nullable disable

namespace NeMobileBg.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230812142734_SeedVehicles")]
    partial class SeedVehicles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Convertible")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = "e45c88c3-c033-422c-869d-dd8840942aeb",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 0",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2000
                        },
                        new
                        {
                            Id = "871f8c4a-8af1-4c84-b05a-cd4a2cc0e2e0",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 1",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 10000,
                            Model = "Model1",
                            Price = 10000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2001
                        },
                        new
                        {
                            Id = "86c4a8d7-cbcf-4b07-adce-2537bf52aa58",
                            Category = "Estate",
                            Color = "White",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 2",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 20000,
                            Model = "Model2",
                            Price = 20000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2002
                        },
                        new
                        {
                            Id = "8951e288-74ac-4064-bfb9-8b02225237f3",
                            Category = "Estate",
                            Color = "Green",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 3",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 30000,
                            Model = "Model3",
                            Price = 30000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2003
                        },
                        new
                        {
                            Id = "32da0e58-929a-4f5d-b096-e8b7d6a9ca69",
                            Category = "Estate",
                            Color = "White",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 4",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 40000,
                            Model = "Model4",
                            Price = 40000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2004
                        },
                        new
                        {
                            Id = "99b23c21-be04-4dbe-a26b-fe479b9565c5",
                            Category = "Estate",
                            Color = "White",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 5",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 50000,
                            Model = "Model5",
                            Price = 50000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2005
                        },
                        new
                        {
                            Id = "0118d801-3738-4c18-a1a7-8365cfaf1115",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 6",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 60000,
                            Model = "Model6",
                            Price = 60000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2006
                        },
                        new
                        {
                            Id = "65c247c4-4090-4e5b-9e3f-41c0a6bcaf89",
                            Category = "Estate",
                            Color = "White",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 7",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 70000,
                            Model = "Model7",
                            Price = 70000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2007
                        },
                        new
                        {
                            Id = "3cc7b998-f044-4b59-a736-da8c35216146",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 8",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 80000,
                            Model = "Model8",
                            Price = 80000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2008
                        },
                        new
                        {
                            Id = "807bc866-6919-4fef-9ce9-9e9247c998c1",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 9",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 90000,
                            Model = "Model9",
                            Price = 90000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2009
                        },
                        new
                        {
                            Id = "1a37253e-f728-40de-9cc1-eece0c226851",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 10",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 100000,
                            Model = "Model10",
                            Price = 100000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2010
                        },
                        new
                        {
                            Id = "27e6fde3-c98d-49c8-b90b-948a0aa48fba",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 11",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 110000,
                            Model = "Model11",
                            Price = 110000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2011
                        },
                        new
                        {
                            Id = "a059ae35-beea-4525-886a-d67205ca7752",
                            Category = "Estate",
                            Color = "Green",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 12",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 120000,
                            Model = "Model12",
                            Price = 120000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2012
                        },
                        new
                        {
                            Id = "4f5fa115-869c-4407-aca0-3c8219369c91",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 13",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 130000,
                            Model = "Model13",
                            Price = 130000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2013
                        },
                        new
                        {
                            Id = "2c0055dd-8ff0-428d-b8c4-e36c39881706",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 14",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 140000,
                            Model = "Model14",
                            Price = 140000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2014
                        },
                        new
                        {
                            Id = "f8a757ad-043e-48a9-8b12-f681104b2602",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 15",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 150000,
                            Model = "Model15",
                            Price = 150000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2015
                        },
                        new
                        {
                            Id = "746766a5-e688-4f3d-ba3d-343a663e0504",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 16",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 160000,
                            Model = "Model16",
                            Price = 160000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2016
                        },
                        new
                        {
                            Id = "a2074234-22aa-4a53-b3e8-1e16a16d5bbe",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 17",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 170000,
                            Model = "Model17",
                            Price = 170000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2017
                        },
                        new
                        {
                            Id = "f5c9d9ce-4fbb-462d-b706-0eec7edba8dc",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 18",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 180000,
                            Model = "Model18",
                            Price = 180000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2018
                        },
                        new
                        {
                            Id = "62d176a7-679b-4adf-9b71-6b05a65acb43",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 19",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 190000,
                            Model = "Model19",
                            Price = 190000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2019
                        },
                        new
                        {
                            Id = "a0ce2b3d-4dc4-4186-9e8f-35099bd13ae9",
                            Category = "Estate",
                            Color = "Green",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 20",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 200000,
                            Model = "Model20",
                            Price = 200000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2020
                        },
                        new
                        {
                            Id = "98d59966-147f-4e7c-ae59-272c094f1a42",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 21",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 210000,
                            Model = "Model21",
                            Price = 210000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2021
                        },
                        new
                        {
                            Id = "c6a9da32-950d-4398-8d21-ef1fd62af989",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            Description = "Description for Car 22",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 220000,
                            Model = "Model22",
                            Price = 220000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Motorcycle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<string>("RequiredLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Motorcycles");

                    b.HasData(
                        new
                        {
                            Id = "8d19c0cf-0e66-4edc-ad27-f8a49ff8208f",
                            Category = "Sport",
                            Color = "White",
                            Condition = "Used",
                            Description = "Description for Car 0",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2000
                        },
                        new
                        {
                            Id = "9780e7f2-421a-4499-8d85-a23a7841380f",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 1",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 100,
                            Model = "Model1",
                            Price = 10000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2001
                        },
                        new
                        {
                            Id = "21ad2539-b955-4470-ac81-ebf764f0d580",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 2",
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 200,
                            Model = "Model2",
                            Price = 20000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2002
                        },
                        new
                        {
                            Id = "36afa6cd-0f71-40f1-986a-b20fae1f78bb",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            Description = "Description for Car 3",
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 300,
                            Model = "Model3",
                            Price = 30000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2003
                        },
                        new
                        {
                            Id = "b5ceb029-de22-4803-83b6-9dcf01e83159",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 4",
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 400,
                            Model = "Model4",
                            Price = 40000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2004
                        },
                        new
                        {
                            Id = "00f49ed2-1598-433f-a9f8-d559bae0b89a",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 5",
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 500,
                            Model = "Model5",
                            Price = 50000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2005
                        },
                        new
                        {
                            Id = "d5eb93f9-fb81-49b6-a22d-963a18e593f9",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 6",
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 600,
                            Model = "Model6",
                            Price = 60000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2006
                        },
                        new
                        {
                            Id = "76c322d3-45a4-4f07-b776-b925c08ad917",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 7",
                            EuroStandard = "Euro 1",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 700,
                            Model = "Model7",
                            Price = 70000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2007
                        },
                        new
                        {
                            Id = "facb0007-fded-4917-9125-0459c8b1d989",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            Description = "Description for Car 8",
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 800,
                            Model = "Model8",
                            Price = 80000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2008
                        },
                        new
                        {
                            Id = "26399eea-229c-446d-9468-06fe6b9d008b",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 9",
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 900,
                            Model = "Model9",
                            Price = 90000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2009
                        },
                        new
                        {
                            Id = "7415ad55-ede4-4a8e-ac2a-c06ccfc41511",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            Description = "Description for Car 10",
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 1000,
                            Model = "Model10",
                            Price = 100000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2010
                        },
                        new
                        {
                            Id = "6001b5e5-ea44-448c-a095-2d3641c890c4",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 11",
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 1100,
                            Model = "Model11",
                            Price = 110000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2011
                        },
                        new
                        {
                            Id = "5a05bc29-0e36-4132-9d2b-95de93456309",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 12",
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 1200,
                            Model = "Model12",
                            Price = 120000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2012
                        },
                        new
                        {
                            Id = "ef84e0de-0db0-414e-8f02-120f3116a4f7",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 13",
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 1300,
                            Model = "Model13",
                            Price = 130000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2013
                        },
                        new
                        {
                            Id = "35c0f1f3-32b5-404f-b39d-8b31d8d730d0",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 14",
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 1400,
                            Model = "Model14",
                            Price = 140000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2014
                        },
                        new
                        {
                            Id = "22447127-94b0-412a-8b43-c9ad8f3a6894",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            Description = "Description for Car 15",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 1500,
                            Model = "Model15",
                            Price = 150000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2015
                        },
                        new
                        {
                            Id = "335ab57c-270f-4e9a-b470-4e1834660d28",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 16",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 1600,
                            Model = "Model16",
                            Price = 160000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2016
                        },
                        new
                        {
                            Id = "af68e7ce-1ae4-40ca-959a-a0de24817592",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            Description = "Description for Car 17",
                            EuroStandard = "Euro 5",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 1700,
                            Model = "Model17",
                            Price = 170000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2017
                        },
                        new
                        {
                            Id = "80b015ba-811d-4721-9305-209e47afe996",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Description for Car 18",
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 1800,
                            Model = "Model18",
                            Price = 180000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2018
                        },
                        new
                        {
                            Id = "85619d0d-4f95-4c25-97b8-7869df3834e6",
                            Category = "Sport",
                            Color = "White",
                            Condition = "Used",
                            Description = "Description for Car 19",
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 1900,
                            Model = "Model19",
                            Price = 190000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2019
                        },
                        new
                        {
                            Id = "7f7bf063-88ae-4e90-b701-7df185af4e3a",
                            Category = "Sport",
                            Color = "White",
                            Condition = "Used",
                            Description = "Description for Car 20",
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 2000,
                            Model = "Model20",
                            Price = 200000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2020
                        },
                        new
                        {
                            Id = "7f31cf7c-5932-46f2-a5c1-68b62a2d4402",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Description for Car 21",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 2100,
                            Model = "Model21",
                            Price = 210000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2021
                        },
                        new
                        {
                            Id = "8f20ae39-6fdf-43b1-9e1b-f2c8458b011f",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Description for Car 22",
                            EuroStandard = "Euro 4",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 2200,
                            Model = "Model22",
                            Price = 220000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Truck", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Axles")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = "3970f922-c8ce-471f-ad0b-5ad9ef65f39f",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 0",
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2000
                        },
                        new
                        {
                            Id = "838e1c1a-729c-4191-94ec-80d4737c03ef",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Description for Car 1",
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 100,
                            Model = "Model1",
                            Price = 10000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2001
                        },
                        new
                        {
                            Id = "10e0b30d-5cec-4a0f-85fa-f26a81d886d5",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 2",
                            EuroStandard = "Euro 2",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 200,
                            Model = "Model2",
                            Price = 20000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2002
                        },
                        new
                        {
                            Id = "57fd16f8-9ff3-4229-887c-16d8c3ac97fa",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            Description = "Description for Car 3",
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 300,
                            Model = "Model3",
                            Price = 30000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2003
                        },
                        new
                        {
                            Id = "3040f82b-bf20-4b5a-bfd4-9936074da328",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 4",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 400,
                            Model = "Model4",
                            Price = 40000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2004
                        },
                        new
                        {
                            Id = "b7567532-53e9-4e50-9445-05ef55a58195",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Description for Car 5",
                            EuroStandard = "Euro 5",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 500,
                            Model = "Model5",
                            Price = 50000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2005
                        },
                        new
                        {
                            Id = "acda0415-f1d1-4844-918e-1a3dce0f8e0a",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 6",
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 600,
                            Model = "Model6",
                            Price = 60000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2006
                        },
                        new
                        {
                            Id = "2c995194-67e8-4987-9916-e29561950601",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 7",
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 700,
                            Model = "Model7",
                            Price = 70000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2007
                        },
                        new
                        {
                            Id = "f242f945-17b9-43ca-8d25-a4723c8176db",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 8",
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 800,
                            Model = "Model8",
                            Price = 80000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2008
                        },
                        new
                        {
                            Id = "a6f7f89a-f993-40ab-84c6-1530f2ca6c4b",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Description for Car 9",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 900,
                            Model = "Model9",
                            Price = 90000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2009
                        },
                        new
                        {
                            Id = "cd02a553-b7f9-4e8d-97f1-a683d5681e81",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 10",
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 1000,
                            Model = "Model10",
                            Price = 100000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2010
                        },
                        new
                        {
                            Id = "9a39a840-8f7b-4f64-9b66-5fffcbb4a9ef",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 11",
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 1100,
                            Model = "Model11",
                            Price = 110000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2011
                        },
                        new
                        {
                            Id = "824bf77b-d3cf-4571-9aaa-f5b5fdbb6e81",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 12",
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 1200,
                            Model = "Model12",
                            Price = 120000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2012
                        },
                        new
                        {
                            Id = "0bde06d5-5fc1-4488-b3a6-314304ccf8ba",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            Description = "Description for Car 13",
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 1300,
                            Model = "Model13",
                            Price = 130000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2013
                        },
                        new
                        {
                            Id = "21b48da4-1d2a-44c3-8a0e-5a74f36fb193",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 14",
                            EuroStandard = "Euro 2",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 1400,
                            Model = "Model14",
                            Price = 140000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2014
                        },
                        new
                        {
                            Id = "43ce5074-f7c2-4012-80f8-c01769b763e6",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            Description = "Description for Car 15",
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 1500,
                            Model = "Model15",
                            Price = 150000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2015
                        },
                        new
                        {
                            Id = "e7aead58-1004-4c90-a8bb-37fcbaabe3aa",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            Description = "Description for Car 16",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 1600,
                            Model = "Model16",
                            Price = 160000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2016
                        },
                        new
                        {
                            Id = "aa1a84f2-a156-448e-94fa-96ff0b434c22",
                            Axles = 8,
                            Color = "Blue",
                            Condition = "Used",
                            Description = "Description for Car 17",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 1700,
                            Model = "Model17",
                            Price = 170000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2017
                        },
                        new
                        {
                            Id = "646b0674-83d6-47f4-8aa9-518ec4c8ab84",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 18",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 1800,
                            Model = "Model18",
                            Price = 180000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2018
                        },
                        new
                        {
                            Id = "48e0c702-a37b-4010-9153-b8de1a4aa787",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 19",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 1900,
                            Model = "Model19",
                            Price = 190000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2019
                        },
                        new
                        {
                            Id = "f5a504fb-c314-49df-a026-ab7b190ccc6f",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 20",
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 2000,
                            Model = "Model20",
                            Price = 200000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2020
                        },
                        new
                        {
                            Id = "3833da4a-76ef-41c9-b897-f48bfbfec16a",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            Description = "Description for Car 21",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 2100,
                            Model = "Model21",
                            Price = 210000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2021
                        },
                        new
                        {
                            Id = "cb87016a-f60b-48fc-99fe-c9c0e3284357",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            Description = "Description for Car 22",
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 2200,
                            Model = "Model22",
                            Price = 220000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Car", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Motorcycle", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Motorcycles")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Truck", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Trucks")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Motorcycles");

                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
