// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeMobileBg.Data;

#nullable disable

namespace NeMobileBg.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230812155920_FixTyposAddCreatedOnVehicle")]
    partial class FixTyposAddCreatedOnVehicle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Convertible")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = "5c83639e-50c2-49fd-b670-eee711bee3e5",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 3:59:20 PM",
                            Description = "Description for Car 0",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2000
                        },
                        new
                        {
                            Id = "a39e4148-f6bd-46d4-9779-0a557bb7bb55",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/11/2023 3:59:20 PM",
                            Description = "Description for Car 1",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 10000,
                            Model = "Model1",
                            Price = 10000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2001
                        },
                        new
                        {
                            Id = "c0bdfab0-6921-47f8-9e1e-f9f46f4ce113",
                            Category = "Estate",
                            Color = "White",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/10/2023 3:59:20 PM",
                            Description = "Description for Car 2",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 20000,
                            Model = "Model2",
                            Price = 20000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2002
                        },
                        new
                        {
                            Id = "05f52fbc-ade9-497a-9e70-b3abb19af17a",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/9/2023 3:59:20 PM",
                            Description = "Description for Car 3",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 30000,
                            Model = "Model3",
                            Price = 30000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2003
                        },
                        new
                        {
                            Id = "52dbcba9-770a-486f-8bca-06218bbc9757",
                            Category = "Estate",
                            Color = "Green",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/8/2023 3:59:20 PM",
                            Description = "Description for Car 4",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 40000,
                            Model = "Model4",
                            Price = 40000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2004
                        },
                        new
                        {
                            Id = "6ee04301-f6a7-491e-9815-49c971f08dce",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/7/2023 3:59:20 PM",
                            Description = "Description for Car 5",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 50000,
                            Model = "Model5",
                            Price = 50000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2005
                        },
                        new
                        {
                            Id = "9f162f16-f5ff-41ad-b9ef-138a3ec57dd1",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/6/2023 3:59:20 PM",
                            Description = "Description for Car 6",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 60000,
                            Model = "Model6",
                            Price = 60000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2006
                        },
                        new
                        {
                            Id = "ce6bc149-0a05-407d-8025-bba45d156a5c",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/5/2023 3:59:20 PM",
                            Description = "Description for Car 7",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 70000,
                            Model = "Model7",
                            Price = 70000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2007
                        },
                        new
                        {
                            Id = "c72128db-01d7-4e9f-9d16-18f1f8aa1c17",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/4/2023 3:59:20 PM",
                            Description = "Description for Car 8",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 80000,
                            Model = "Model8",
                            Price = 80000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2008
                        },
                        new
                        {
                            Id = "92b7d51c-60ca-49e7-9ba9-d0bf92942a66",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/3/2023 3:59:20 PM",
                            Description = "Description for Car 9",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 90000,
                            Model = "Model9",
                            Price = 90000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2009
                        },
                        new
                        {
                            Id = "8015685f-d931-4a10-bddc-5cc33ec4e74f",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/2/2023 3:59:20 PM",
                            Description = "Description for Car 10",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 100000,
                            Model = "Model10",
                            Price = 100000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2010
                        },
                        new
                        {
                            Id = "f6e5c0be-47cc-46eb-8c3f-da5c9de3d5e3",
                            Category = "Estate",
                            Color = "Green",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/1/2023 3:59:20 PM",
                            Description = "Description for Car 11",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 110000,
                            Model = "Model11",
                            Price = 110000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2011
                        },
                        new
                        {
                            Id = "668815fa-e6a9-4d48-952d-20e8d7a6743c",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/31/2023 3:59:20 PM",
                            Description = "Description for Car 12",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 120000,
                            Model = "Model12",
                            Price = 120000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2012
                        },
                        new
                        {
                            Id = "2bd24005-4ce7-47cd-a446-9ebd0b7aa69e",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/30/2023 3:59:20 PM",
                            Description = "Description for Car 13",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 130000,
                            Model = "Model13",
                            Price = 130000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2013
                        },
                        new
                        {
                            Id = "1738935d-6b7b-448c-96dc-08df7c21f9c9",
                            Category = "Estate",
                            Color = "Green",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/29/2023 3:59:20 PM",
                            Description = "Description for Car 14",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 140000,
                            Model = "Model14",
                            Price = 140000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2014
                        },
                        new
                        {
                            Id = "0d4d74d6-65fd-4a1b-924e-1e77e93d93da",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/28/2023 3:59:20 PM",
                            Description = "Description for Car 15",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 150000,
                            Model = "Model15",
                            Price = 150000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2015
                        },
                        new
                        {
                            Id = "13eb7d0e-400d-44b4-a0af-22754f32e96e",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/27/2023 3:59:20 PM",
                            Description = "Description for Car 16",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 160000,
                            Model = "Model16",
                            Price = 160000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2016
                        },
                        new
                        {
                            Id = "83e06700-9de9-438c-b482-a079ea8d2c82",
                            Category = "Estate",
                            Color = "White",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/26/2023 3:59:20 PM",
                            Description = "Description for Car 17",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 170000,
                            Model = "Model17",
                            Price = 170000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2017
                        },
                        new
                        {
                            Id = "61074e77-be88-4da6-acb0-54f4dfe92eab",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/25/2023 3:59:20 PM",
                            Description = "Description for Car 18",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 180000,
                            Model = "Model18",
                            Price = 180000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2018
                        },
                        new
                        {
                            Id = "a01c0d18-25d3-4f65-91e6-b2b02c28b291",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/24/2023 3:59:20 PM",
                            Description = "Description for Car 19",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 190000,
                            Model = "Model19",
                            Price = 190000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2019
                        },
                        new
                        {
                            Id = "dc67d0c5-0768-47da-a11f-bc1e65e33133",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/23/2023 3:59:20 PM",
                            Description = "Description for Car 20",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 200000,
                            Model = "Model20",
                            Price = 200000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2020
                        },
                        new
                        {
                            Id = "5a0a8bcc-da0f-41ec-b135-c7719434abff",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/22/2023 3:59:20 PM",
                            Description = "Description for Car 21",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 210000,
                            Model = "Model21",
                            Price = 210000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2021
                        },
                        new
                        {
                            Id = "0259a114-1291-4c76-b097-8fbe5ab0b60e",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "7/21/2023 3:59:20 PM",
                            Description = "Description for Car 22",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 220000,
                            Model = "Model22",
                            Price = 220000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Motorcycle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<string>("RequiredLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Motorcycles");

                    b.HasData(
                        new
                        {
                            Id = "c21094e2-1992-4d21-8ac9-17555424627a",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 3:59:20 PM",
                            Description = "Description for Car 0",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2000
                        },
                        new
                        {
                            Id = "71b46df0-0e7e-4a98-a56a-ed2a080522db",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 3:59:20 PM",
                            Description = "Description for Car 1",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 100,
                            Model = "Model1",
                            Price = 10000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2001
                        },
                        new
                        {
                            Id = "daa643cf-fa51-4eca-be5b-cd67e59be3f7",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/10/2023 3:59:20 PM",
                            Description = "Description for Car 2",
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 200,
                            Model = "Model2",
                            Price = 20000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2002
                        },
                        new
                        {
                            Id = "baa01e18-aba5-43e9-a33e-86604ddfcfce",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/9/2023 3:59:20 PM",
                            Description = "Description for Car 3",
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 300,
                            Model = "Model3",
                            Price = 30000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2003
                        },
                        new
                        {
                            Id = "d92e687d-8346-4204-ac42-9cf56206b674",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/8/2023 3:59:20 PM",
                            Description = "Description for Car 4",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 400,
                            Model = "Model4",
                            Price = 40000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2004
                        },
                        new
                        {
                            Id = "50d31768-4944-4924-a37a-254dbbdf73e9",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/7/2023 3:59:20 PM",
                            Description = "Description for Car 5",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 500,
                            Model = "Model5",
                            Price = 50000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2005
                        },
                        new
                        {
                            Id = "0e5eb7e6-5dd9-45b3-82b2-7102fe862fad",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/6/2023 3:59:20 PM",
                            Description = "Description for Car 6",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 600,
                            Model = "Model6",
                            Price = 60000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2006
                        },
                        new
                        {
                            Id = "fa0942f6-e945-4c3d-9661-cd50ccfc9150",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/5/2023 3:59:20 PM",
                            Description = "Description for Car 7",
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 700,
                            Model = "Model7",
                            Price = 70000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2007
                        },
                        new
                        {
                            Id = "18eb55a0-61f5-4ce2-b609-429f0e35a4d2",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/4/2023 3:59:20 PM",
                            Description = "Description for Car 8",
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 800,
                            Model = "Model8",
                            Price = 80000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2008
                        },
                        new
                        {
                            Id = "8a599716-d306-4fa0-847c-56c31df2aada",
                            Category = "Sport",
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "8/3/2023 3:59:20 PM",
                            Description = "Description for Car 9",
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 900,
                            Model = "Model9",
                            Price = 90000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2009
                        },
                        new
                        {
                            Id = "ee61cd07-b4a9-4a2b-9799-7ab6d87db37d",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/2/2023 3:59:20 PM",
                            Description = "Description for Car 10",
                            EuroStandard = "Euro 4",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 1000,
                            Model = "Model10",
                            Price = 100000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2010
                        },
                        new
                        {
                            Id = "84fd9920-583d-4511-a050-c9818d37ecb5",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/1/2023 3:59:20 PM",
                            Description = "Description for Car 11",
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 1100,
                            Model = "Model11",
                            Price = 110000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2011
                        },
                        new
                        {
                            Id = "5334efa2-9a77-4a42-9794-ef623c4841e6",
                            Category = "Sport",
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "7/31/2023 3:59:20 PM",
                            Description = "Description for Car 12",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 1200,
                            Model = "Model12",
                            Price = 120000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2012
                        },
                        new
                        {
                            Id = "ff999e2f-d5f2-475a-bbf2-290e87b26f7b",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "7/30/2023 3:59:20 PM",
                            Description = "Description for Car 13",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 1300,
                            Model = "Model13",
                            Price = 130000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2013
                        },
                        new
                        {
                            Id = "7e52f5fd-480a-4543-bc14-e8279d76b56e",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "7/29/2023 3:59:20 PM",
                            Description = "Description for Car 14",
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 1400,
                            Model = "Model14",
                            Price = 140000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2014
                        },
                        new
                        {
                            Id = "aed8bf9f-300d-4f14-9be5-779378179d42",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "7/28/2023 3:59:20 PM",
                            Description = "Description for Car 15",
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 1500,
                            Model = "Model15",
                            Price = 150000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2015
                        },
                        new
                        {
                            Id = "92e1d435-e7ca-4dbf-866f-4a2dd75dc490",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "7/27/2023 3:59:20 PM",
                            Description = "Description for Car 16",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 1600,
                            Model = "Model16",
                            Price = 160000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2016
                        },
                        new
                        {
                            Id = "89098372-7ca4-41ff-b611-4cded9d86b08",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "7/26/2023 3:59:20 PM",
                            Description = "Description for Car 17",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 1700,
                            Model = "Model17",
                            Price = 170000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2017
                        },
                        new
                        {
                            Id = "ae03b05a-b2db-4ce2-ab69-e7400f61883d",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "7/25/2023 3:59:20 PM",
                            Description = "Description for Car 18",
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 1800,
                            Model = "Model18",
                            Price = 180000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2018
                        },
                        new
                        {
                            Id = "49e57277-84ab-4103-aba9-f126ad59b74c",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "7/24/2023 3:59:20 PM",
                            Description = "Description for Car 19",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 1900,
                            Model = "Model19",
                            Price = 190000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2019
                        },
                        new
                        {
                            Id = "0111ee4b-6eed-48fb-8f92-45757f5e866f",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "7/23/2023 3:59:20 PM",
                            Description = "Description for Car 20",
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 2000,
                            Model = "Model20",
                            Price = 200000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2020
                        },
                        new
                        {
                            Id = "989bf659-88df-4741-9aee-5aca3aeef20f",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "7/22/2023 3:59:20 PM",
                            Description = "Description for Car 21",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 2100,
                            Model = "Model21",
                            Price = 210000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2021
                        },
                        new
                        {
                            Id = "f458dd55-de40-4f83-a8b1-e04d2b7dbed0",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "7/21/2023 3:59:20 PM",
                            Description = "Description for Car 22",
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 2200,
                            Model = "Model22",
                            Price = 220000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Truck", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Axles")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = "684558e1-8dee-4929-b84b-60e6ec67c92a",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 3:59:20 PM",
                            Description = "Description for Car 0",
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2000
                        },
                        new
                        {
                            Id = "70f25f78-f9a2-4bbf-a65b-acd423b5dde0",
                            Axles = 8,
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 3:59:20 PM",
                            Description = "Description for Car 1",
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 100,
                            Model = "Model1",
                            Price = 10000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2001
                        },
                        new
                        {
                            Id = "f001b0c3-c814-4be1-8892-b791d882e48a",
                            Axles = 8,
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "8/10/2023 3:59:20 PM",
                            Description = "Description for Car 2",
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 200,
                            Model = "Model2",
                            Price = 20000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2002
                        },
                        new
                        {
                            Id = "5b520003-8b97-4d5d-907b-aa12ee569588",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/9/2023 3:59:20 PM",
                            Description = "Description for Car 3",
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 300,
                            Model = "Model3",
                            Price = 30000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2003
                        },
                        new
                        {
                            Id = "e60bb9de-8d04-46d4-b4d8-f312d62473a9",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/8/2023 3:59:20 PM",
                            Description = "Description for Car 4",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 400,
                            Model = "Model4",
                            Price = 40000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2004
                        },
                        new
                        {
                            Id = "a242fd1f-b6d6-432a-a90f-211c6373b926",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/7/2023 3:59:20 PM",
                            Description = "Description for Car 5",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 500,
                            Model = "Model5",
                            Price = 50000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2005
                        },
                        new
                        {
                            Id = "05688b4c-8469-4cf7-b3e4-81cb04b99d6f",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/6/2023 3:59:20 PM",
                            Description = "Description for Car 6",
                            EuroStandard = "Euro 0",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 600,
                            Model = "Model6",
                            Price = 60000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2006
                        },
                        new
                        {
                            Id = "445e5797-6ade-48b2-8f16-b38f4f0dab75",
                            Axles = 8,
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/5/2023 3:59:20 PM",
                            Description = "Description for Car 7",
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 700,
                            Model = "Model7",
                            Price = 70000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2007
                        },
                        new
                        {
                            Id = "e06ae97a-731d-4e26-88ef-dda94002927a",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/4/2023 3:59:20 PM",
                            Description = "Description for Car 8",
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 800,
                            Model = "Model8",
                            Price = 80000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2008
                        },
                        new
                        {
                            Id = "ed4967d3-02cf-4499-baa5-3f6f9e7a722e",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/3/2023 3:59:20 PM",
                            Description = "Description for Car 9",
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 900,
                            Model = "Model9",
                            Price = 90000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2009
                        },
                        new
                        {
                            Id = "1baa69af-11ab-43e7-bbe9-9b358c193bf8",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/2/2023 3:59:20 PM",
                            Description = "Description for Car 10",
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 1000,
                            Model = "Model10",
                            Price = 100000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2010
                        },
                        new
                        {
                            Id = "cb03141e-2209-4e3a-b874-520202048a31",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/1/2023 3:59:20 PM",
                            Description = "Description for Car 11",
                            EuroStandard = "Euro 5",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 1100,
                            Model = "Model11",
                            Price = 110000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2011
                        },
                        new
                        {
                            Id = "c5685f95-02b9-43aa-9c05-9563213d5dba",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "7/31/2023 3:59:20 PM",
                            Description = "Description for Car 12",
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 1200,
                            Model = "Model12",
                            Price = 120000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2012
                        },
                        new
                        {
                            Id = "d8250942-12b1-45fd-96ae-53734e57fed1",
                            Axles = 8,
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "7/30/2023 3:59:20 PM",
                            Description = "Description for Car 13",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 1300,
                            Model = "Model13",
                            Price = 130000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2013
                        },
                        new
                        {
                            Id = "f8fb21c6-1e75-40e3-91f7-61834d208118",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "7/29/2023 3:59:20 PM",
                            Description = "Description for Car 14",
                            EuroStandard = "Euro 2",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 1400,
                            Model = "Model14",
                            Price = 140000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2014
                        },
                        new
                        {
                            Id = "780357b7-9609-43c9-b7ec-27b17d4f18d2",
                            Axles = 8,
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "7/28/2023 3:59:20 PM",
                            Description = "Description for Car 15",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 1500,
                            Model = "Model15",
                            Price = 150000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2015
                        },
                        new
                        {
                            Id = "f3a3918a-ffc6-42ab-80b7-f4dfb74f5d96",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "7/27/2023 3:59:20 PM",
                            Description = "Description for Car 16",
                            EuroStandard = "Euro 4",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 1600,
                            Model = "Model16",
                            Price = 160000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2016
                        },
                        new
                        {
                            Id = "834c9bb8-0e2f-4fd3-bd0b-57a1df70c190",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "7/26/2023 3:59:20 PM",
                            Description = "Description for Car 17",
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 1700,
                            Model = "Model17",
                            Price = 170000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2017
                        },
                        new
                        {
                            Id = "0069bbc0-3322-4f36-9fc0-87d989230640",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "7/25/2023 3:59:20 PM",
                            Description = "Description for Car 18",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 1800,
                            Model = "Model18",
                            Price = 180000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2018
                        },
                        new
                        {
                            Id = "cb4a974d-e639-46b4-a3dd-acd9c82567af",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "7/24/2023 3:59:20 PM",
                            Description = "Description for Car 19",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 1900,
                            Model = "Model19",
                            Price = 190000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2019
                        },
                        new
                        {
                            Id = "2b261127-ec99-45ec-835e-b8dd8950490f",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "7/23/2023 3:59:20 PM",
                            Description = "Description for Car 20",
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 2000,
                            Model = "Model20",
                            Price = 200000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2020
                        },
                        new
                        {
                            Id = "def990a6-66e7-49a6-8176-015e75a30fc7",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "7/22/2023 3:59:20 PM",
                            Description = "Description for Car 21",
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 2100,
                            Model = "Model21",
                            Price = 210000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2021
                        },
                        new
                        {
                            Id = "58f51f62-6f58-471d-94c2-550f4e7e8c0b",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "7/21/2023 3:59:20 PM",
                            Description = "Description for Car 22",
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 2200,
                            Model = "Model22",
                            Price = 220000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Tyre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOT")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Inches")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeedIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyreIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tyres");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Car", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Motorcycle", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Motorcycles")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Truck", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Trucks")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Tyre", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Motorcycles");

                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
