// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeMobileBg.Data;

#nullable disable

namespace NeMobileBg.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230812160159_FixSeeders")]
    partial class FixSeeders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Convertible")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = "0f882459-b612-4740-be47-d71306ecd9ff",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 4:01:59 PM",
                            Description = "Description for Car 0",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2000
                        },
                        new
                        {
                            Id = "9e5cefab-b6f1-4e0a-a53e-cafaf6d29374",
                            Category = "Estate",
                            Color = "Green",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 3:01:59 PM",
                            Description = "Description for Car 1",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 10000,
                            Model = "Model1",
                            Price = 10000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2001
                        },
                        new
                        {
                            Id = "4abed4c3-73d6-4da3-aee0-ff842d719334",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 2:01:59 PM",
                            Description = "Description for Car 2",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 20000,
                            Model = "Model2",
                            Price = 20000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2002
                        },
                        new
                        {
                            Id = "29800fd5-5b01-4fc0-bc1c-1a7ca77d811c",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 1:01:59 PM",
                            Description = "Description for Car 3",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 30000,
                            Model = "Model3",
                            Price = 30000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2003
                        },
                        new
                        {
                            Id = "2525b0b7-4268-48de-b00b-0061de301c34",
                            Category = "Estate",
                            Color = "White",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 12:01:59 PM",
                            Description = "Description for Car 4",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 40000,
                            Model = "Model4",
                            Price = 40000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2004
                        },
                        new
                        {
                            Id = "b76cb111-c048-4026-a877-6b377c223af7",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 11:01:59 AM",
                            Description = "Description for Car 5",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 50000,
                            Model = "Model5",
                            Price = 50000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2005
                        },
                        new
                        {
                            Id = "31b46e86-02a7-4acb-a71c-984c42add518",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 10:01:59 AM",
                            Description = "Description for Car 6",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 60000,
                            Model = "Model6",
                            Price = 60000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2006
                        },
                        new
                        {
                            Id = "d25fd6e4-b1ea-4a30-a3c1-3ea187adb845",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 9:01:59 AM",
                            Description = "Description for Car 7",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 70000,
                            Model = "Model7",
                            Price = 70000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2007
                        },
                        new
                        {
                            Id = "f8424a22-fc5a-4fc5-aca4-1d0738c478e3",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 8:01:59 AM",
                            Description = "Description for Car 8",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 80000,
                            Model = "Model8",
                            Price = 80000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2008
                        },
                        new
                        {
                            Id = "31a9fea8-f517-40aa-af54-9125805746f0",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 7:01:59 AM",
                            Description = "Description for Car 9",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 90000,
                            Model = "Model9",
                            Price = 90000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2009
                        },
                        new
                        {
                            Id = "196debe0-83e4-45df-a55a-2a192118300a",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 6:01:59 AM",
                            Description = "Description for Car 10",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 100000,
                            Model = "Model10",
                            Price = 100000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2010
                        },
                        new
                        {
                            Id = "1cd5e968-52e9-4189-ab75-b297a73df5ae",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 5:01:59 AM",
                            Description = "Description for Car 11",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 110000,
                            Model = "Model11",
                            Price = 110000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2011
                        },
                        new
                        {
                            Id = "85df6b92-311f-4cad-85d7-d229133ae146",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 4:01:59 AM",
                            Description = "Description for Car 12",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 120000,
                            Model = "Model12",
                            Price = 120000m,
                            Seats = 4,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2012
                        },
                        new
                        {
                            Id = "03b95919-251c-4a88-9241-7e15a47fd6e2",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 3:01:59 AM",
                            Description = "Description for Car 13",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 130000,
                            Model = "Model13",
                            Price = 130000m,
                            Seats = 4,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2013
                        },
                        new
                        {
                            Id = "ae9e865f-9704-403d-87b5-5efb914836e3",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 2:01:59 AM",
                            Description = "Description for Car 14",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 140000,
                            Model = "Model14",
                            Price = 140000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2014
                        },
                        new
                        {
                            Id = "a2844969-ea0c-4989-9d33-055d811154ca",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 1:01:59 AM",
                            Description = "Description for Car 15",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 150000,
                            Model = "Model15",
                            Price = 150000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2015
                        },
                        new
                        {
                            Id = "7a06bf8a-9117-4474-b1c2-ac3a9e700a6b",
                            Category = "Estate",
                            Color = "Silver",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/12/2023 12:01:59 AM",
                            Description = "Description for Car 16",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 160000,
                            Model = "Model16",
                            Price = 160000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2016
                        },
                        new
                        {
                            Id = "bf62e723-d384-4971-a793-3115c9afb3c5",
                            Category = "Estate",
                            Color = "Blue",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/11/2023 11:01:59 PM",
                            Description = "Description for Car 17",
                            Doors = 4,
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 170000,
                            Model = "Model17",
                            Price = 170000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2017
                        },
                        new
                        {
                            Id = "e8ec195b-ce67-42c0-8313-40a63b5969ba",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/11/2023 10:01:59 PM",
                            Description = "Description for Car 18",
                            Doors = 4,
                            EuroStandard = "Euro 0",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 180000,
                            Model = "Model18",
                            Price = 180000m,
                            Seats = 4,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2018
                        },
                        new
                        {
                            Id = "05de434a-b0aa-4de5-9f0a-0e513f0adcc6",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/11/2023 9:01:59 PM",
                            Description = "Description for Car 19",
                            Doors = 4,
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 190000,
                            Model = "Model19",
                            Price = 190000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2019
                        },
                        new
                        {
                            Id = "00eed369-75ef-4c1f-aac3-45aec7798318",
                            Category = "Estate",
                            Color = "Black",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/11/2023 8:01:59 PM",
                            Description = "Description for Car 20",
                            Doors = 4,
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 200000,
                            Model = "Model20",
                            Price = 200000m,
                            Seats = 4,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2020
                        },
                        new
                        {
                            Id = "8265ce83-5f08-436b-b98a-0cda6cd42077",
                            Category = "Estate",
                            Color = "Gray",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/11/2023 7:01:59 PM",
                            Description = "Description for Car 21",
                            Doors = 4,
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 210000,
                            Model = "Model21",
                            Price = 210000m,
                            Seats = 4,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2021
                        },
                        new
                        {
                            Id = "d079d15c-3807-46ec-bd2f-7b5af6c4efbd",
                            Category = "Estate",
                            Color = "Red",
                            Condition = "Used",
                            Convertible = false,
                            CreatedOn = "8/11/2023 6:01:59 PM",
                            Description = "Description for Car 22",
                            Doors = 4,
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 220000,
                            Model = "Model22",
                            Price = 220000m,
                            Seats = 4,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Motorcycle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<string>("RequiredLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Motorcycles");

                    b.HasData(
                        new
                        {
                            Id = "5f1deb33-1a08-4e84-97d3-fde103269b04",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 4:01:59 PM",
                            Description = "Description for Car 0",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 100,
                            Make = "Brand0",
                            Mileage = 0,
                            Model = "Model0",
                            Price = 0m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2000
                        },
                        new
                        {
                            Id = "014ee855-348f-40c1-9bfa-9c04ef145016",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 3:01:59 PM",
                            Description = "Description for Car 1",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 100,
                            Model = "Model1",
                            Price = 10000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2001
                        },
                        new
                        {
                            Id = "9dddae38-46f4-41e8-b80d-e40a59e6b7c6",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 2:01:59 PM",
                            Description = "Description for Car 2",
                            EuroStandard = "Euro 2",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 200,
                            Model = "Model2",
                            Price = 20000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2002
                        },
                        new
                        {
                            Id = "493695a0-3326-4b0e-a5fe-6083179ffb06",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 1:01:59 PM",
                            Description = "Description for Car 3",
                            EuroStandard = "Euro 3",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 300,
                            Model = "Model3",
                            Price = 30000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2003
                        },
                        new
                        {
                            Id = "257c1149-fa18-41b9-b551-4d1256605a20",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 12:01:59 PM",
                            Description = "Description for Car 4",
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 400,
                            Model = "Model4",
                            Price = 40000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2004
                        },
                        new
                        {
                            Id = "5a330e30-376c-4189-b5bb-f0a828254624",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 11:01:59 AM",
                            Description = "Description for Car 5",
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 500,
                            Model = "Model5",
                            Price = 50000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2005
                        },
                        new
                        {
                            Id = "19f32536-021d-4e7c-aa62-a4f980b813fc",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 10:01:59 AM",
                            Description = "Description for Car 6",
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 600,
                            Model = "Model6",
                            Price = 60000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2006
                        },
                        new
                        {
                            Id = "87ec8bdf-6eb2-4845-acd9-0fdd8460fdd3",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 9:01:59 AM",
                            Description = "Description for Car 7",
                            EuroStandard = "Euro 1",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 700,
                            Model = "Model7",
                            Price = 70000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2007
                        },
                        new
                        {
                            Id = "9a80db65-008e-4d80-893e-84db1b007a3a",
                            Category = "Sport",
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 8:01:59 AM",
                            Description = "Description for Car 8",
                            EuroStandard = "Euro 2",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 800,
                            Model = "Model8",
                            Price = 80000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2008
                        },
                        new
                        {
                            Id = "a2604a18-ea3d-4420-bbd2-676554d0afb2",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 7:01:59 AM",
                            Description = "Description for Car 9",
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 900,
                            Model = "Model9",
                            Price = 90000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2009
                        },
                        new
                        {
                            Id = "75970fe8-009a-4e27-9141-00ac349d48ee",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 6:01:59 AM",
                            Description = "Description for Car 10",
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 1000,
                            Model = "Model10",
                            Price = 100000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2010
                        },
                        new
                        {
                            Id = "00c7f291-2327-402f-ab94-df681a007bd9",
                            Category = "Sport",
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 5:01:59 AM",
                            Description = "Description for Car 11",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 1100,
                            Model = "Model11",
                            Price = 110000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2011
                        },
                        new
                        {
                            Id = "673c705d-09fe-460f-8ebb-67bad618572a",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 4:01:59 AM",
                            Description = "Description for Car 12",
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 1200,
                            Model = "Model12",
                            Price = 120000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2012
                        },
                        new
                        {
                            Id = "e928c4dc-dfc2-43ad-aca3-75bbd8bf9be5",
                            Category = "Sport",
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 3:01:59 AM",
                            Description = "Description for Car 13",
                            EuroStandard = "Euro 1",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 1300,
                            Model = "Model13",
                            Price = 130000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2013
                        },
                        new
                        {
                            Id = "f24258aa-ecd7-4e6a-8c0f-3b06e7c0ef91",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 2:01:59 AM",
                            Description = "Description for Car 14",
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 1400,
                            Model = "Model14",
                            Price = 140000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2014
                        },
                        new
                        {
                            Id = "6ee85bac-7abc-416b-8e48-b26e44996071",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 1:01:59 AM",
                            Description = "Description for Car 15",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 1500,
                            Model = "Model15",
                            Price = 150000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2015
                        },
                        new
                        {
                            Id = "1b389d3c-865b-49dd-bf2e-bd846b59bdb4",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 12:01:59 AM",
                            Description = "Description for Car 16",
                            EuroStandard = "Euro 4",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 1600,
                            Model = "Model16",
                            Price = 160000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2016
                        },
                        new
                        {
                            Id = "10e72665-bdbf-4f37-9eec-0d0076a7351e",
                            Category = "Sport",
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 11:01:59 PM",
                            Description = "Description for Car 17",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 1700,
                            Model = "Model17",
                            Price = 170000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2017
                        },
                        new
                        {
                            Id = "cde9d492-aaf0-4acc-a8c7-cb72de302e24",
                            Category = "Sport",
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 10:01:59 PM",
                            Description = "Description for Car 18",
                            EuroStandard = "Euro 0",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 1800,
                            Model = "Model18",
                            Price = 180000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2018
                        },
                        new
                        {
                            Id = "3c558c10-82f6-41ba-abdf-bc889957e87a",
                            Category = "Sport",
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 9:01:59 PM",
                            Description = "Description for Car 19",
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 1900,
                            Model = "Model19",
                            Price = 190000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2019
                        },
                        new
                        {
                            Id = "2076282a-fd7b-423f-b729-a8b8ef47ac61",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 8:01:59 PM",
                            Description = "Description for Car 20",
                            EuroStandard = "Euro 2",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 2000,
                            Model = "Model20",
                            Price = 200000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2020
                        },
                        new
                        {
                            Id = "3c6a0993-3073-45ba-8f86-01c28f71fce3",
                            Category = "Sport",
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 7:01:59 PM",
                            Description = "Description for Car 21",
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 2100,
                            Model = "Model21",
                            Price = 210000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2021
                        },
                        new
                        {
                            Id = "f173fbe7-a788-4be8-8a28-b72a0673f570",
                            Category = "Sport",
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 6:01:59 PM",
                            Description = "Description for Car 22",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 2200,
                            Model = "Model22",
                            Price = 220000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Truck", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Axles")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuroStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gearbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = "6b33fc91-7ba5-47ae-b2d8-21d0aa7b9de2",
                            Axles = 8,
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 3:01:59 PM",
                            Description = "Description for Car 1",
                            EuroStandard = "Euro 1",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 101,
                            Make = "Brand1",
                            Mileage = 100,
                            Model = "Model1",
                            Price = 10000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2001
                        },
                        new
                        {
                            Id = "dd0d4689-ad66-4ee1-9376-4938aaed3fa5",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 2:01:59 PM",
                            Description = "Description for Car 2",
                            EuroStandard = "Euro 2",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 102,
                            Make = "Brand2",
                            Mileage = 200,
                            Model = "Model2",
                            Price = 20000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2002
                        },
                        new
                        {
                            Id = "a4eae417-1a3b-4943-9f28-b4f7e31190af",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 1:01:59 PM",
                            Description = "Description for Car 3",
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 103,
                            Make = "Brand3",
                            Mileage = 300,
                            Model = "Model3",
                            Price = 30000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2003
                        },
                        new
                        {
                            Id = "ad7addbb-9559-413a-bfd7-bef92f56f7b1",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 12:01:59 PM",
                            Description = "Description for Car 4",
                            EuroStandard = "Euro 4",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 104,
                            Make = "Brand4",
                            Mileage = 400,
                            Model = "Model4",
                            Price = 40000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2004
                        },
                        new
                        {
                            Id = "351eb134-8a06-4a65-8d12-79869af82ec1",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 11:01:59 AM",
                            Description = "Description for Car 5",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 105,
                            Make = "Brand5",
                            Mileage = 500,
                            Model = "Model5",
                            Price = 50000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2005
                        },
                        new
                        {
                            Id = "d08feaf2-6875-4f43-ac35-2a7e4b59a000",
                            Axles = 8,
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 10:01:59 AM",
                            Description = "Description for Car 6",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 106,
                            Make = "Brand6",
                            Mileage = 600,
                            Model = "Model6",
                            Price = 60000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2006
                        },
                        new
                        {
                            Id = "a6f07ee9-6435-4f45-b487-e969984b128f",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 9:01:59 AM",
                            Description = "Description for Car 7",
                            EuroStandard = "Euro 1",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 107,
                            Make = "Brand7",
                            Mileage = 700,
                            Model = "Model7",
                            Price = 70000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2007
                        },
                        new
                        {
                            Id = "cb08fd25-7c2c-4013-a7b9-35a8e50727a4",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 8:01:59 AM",
                            Description = "Description for Car 8",
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 108,
                            Make = "Brand8",
                            Mileage = 800,
                            Model = "Model8",
                            Price = 80000m,
                            UserId = "5856091b-d323-445d-a07b-5c28db656393",
                            Year = 2008
                        },
                        new
                        {
                            Id = "36b05f0f-96e5-4c7a-8b02-a17a0f831957",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 7:01:59 AM",
                            Description = "Description for Car 9",
                            EuroStandard = "Euro 3",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 109,
                            Make = "Brand9",
                            Mileage = 900,
                            Model = "Model9",
                            Price = 90000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2009
                        },
                        new
                        {
                            Id = "977a7ff5-ab78-41a6-b554-48e30992b49d",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 6:01:59 AM",
                            Description = "Description for Car 10",
                            EuroStandard = "Euro 4",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 110,
                            Make = "Brand10",
                            Mileage = 1000,
                            Model = "Model10",
                            Price = 100000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2010
                        },
                        new
                        {
                            Id = "12e23e59-7da0-43c4-b3d4-ebc6e5b99af4",
                            Axles = 8,
                            Color = "Blue",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 5:01:59 AM",
                            Description = "Description for Car 11",
                            EuroStandard = "Euro 5",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 111,
                            Make = "Brand11",
                            Mileage = 1100,
                            Model = "Model11",
                            Price = 110000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2011
                        },
                        new
                        {
                            Id = "3d108ad2-2cd4-410e-9976-c1ff0318b18e",
                            Axles = 8,
                            Color = "Green",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 4:01:59 AM",
                            Description = "Description for Car 12",
                            EuroStandard = "Euro 0",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 112,
                            Make = "Brand12",
                            Mileage = 1200,
                            Model = "Model12",
                            Price = 120000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2012
                        },
                        new
                        {
                            Id = "e88376ac-5027-4e58-80ae-fdf2d514fac9",
                            Axles = 8,
                            Color = "Red",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 3:01:59 AM",
                            Description = "Description for Car 13",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Manual",
                            HorsePower = 113,
                            Make = "Brand13",
                            Mileage = 1300,
                            Model = "Model13",
                            Price = 130000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2013
                        },
                        new
                        {
                            Id = "0cf0c107-9331-4a90-9360-19783a023233",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 2:01:59 AM",
                            Description = "Description for Car 14",
                            EuroStandard = "Euro 2",
                            FuelType = "Gasoline",
                            Gearbox = "Manual",
                            HorsePower = 114,
                            Make = "Brand14",
                            Mileage = 1400,
                            Model = "Model14",
                            Price = 140000m,
                            UserId = "037f69eb-1390-435f-a085-e738fb60e93e",
                            Year = 2014
                        },
                        new
                        {
                            Id = "27acf7d6-d24d-4389-be88-03610926a6f6",
                            Axles = 8,
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 1:01:59 AM",
                            Description = "Description for Car 15",
                            EuroStandard = "Euro 3",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 115,
                            Make = "Brand15",
                            Mileage = 1500,
                            Model = "Model15",
                            Price = 150000m,
                            UserId = "296290bd-402b-4dc7-922f-3586f8d0c882",
                            Year = 2015
                        },
                        new
                        {
                            Id = "14fbf992-d8f2-4dbc-b240-865574f8b3ec",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/12/2023 12:01:59 AM",
                            Description = "Description for Car 16",
                            EuroStandard = "Euro 4",
                            FuelType = "Diesel",
                            Gearbox = "Manual",
                            HorsePower = 116,
                            Make = "Brand16",
                            Mileage = 1600,
                            Model = "Model16",
                            Price = 160000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2016
                        },
                        new
                        {
                            Id = "f79a1033-2717-4d0f-b603-045791edd55f",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 11:01:59 PM",
                            Description = "Description for Car 17",
                            EuroStandard = "Euro 5",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 117,
                            Make = "Brand17",
                            Mileage = 1700,
                            Model = "Model17",
                            Price = 170000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2017
                        },
                        new
                        {
                            Id = "4e409774-0eec-4cb5-ad68-0c8d3a3be3bf",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 10:01:59 PM",
                            Description = "Description for Car 18",
                            EuroStandard = "Euro 0",
                            FuelType = "Electric",
                            Gearbox = "Manual",
                            HorsePower = 118,
                            Make = "Brand18",
                            Mileage = 1800,
                            Model = "Model18",
                            Price = 180000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2018
                        },
                        new
                        {
                            Id = "8fa71bc6-6596-4736-ab6c-e1f6d3dfc551",
                            Axles = 8,
                            Color = "Silver",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 9:01:59 PM",
                            Description = "Description for Car 19",
                            EuroStandard = "Euro 1",
                            FuelType = "Hybrid",
                            Gearbox = "Automatic",
                            HorsePower = 119,
                            Make = "Brand19",
                            Mileage = 1900,
                            Model = "Model19",
                            Price = 190000m,
                            UserId = "3035f543-8ce5-457d-8073-c086473cf18a",
                            Year = 2019
                        },
                        new
                        {
                            Id = "adb8ed3a-b0ec-4c40-9c1c-3f57117c6011",
                            Axles = 8,
                            Color = "White",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 8:01:59 PM",
                            Description = "Description for Car 20",
                            EuroStandard = "Euro 2",
                            FuelType = "Electric",
                            Gearbox = "Automatic",
                            HorsePower = 120,
                            Make = "Brand20",
                            Mileage = 2000,
                            Model = "Model20",
                            Price = 200000m,
                            UserId = "4a73c6d5-f1be-478f-af3f-e81d3ab8fbe5",
                            Year = 2020
                        },
                        new
                        {
                            Id = "42e3a33c-e4ec-4a70-8635-e0dfa2306b14",
                            Axles = 8,
                            Color = "Gray",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 7:01:59 PM",
                            Description = "Description for Car 21",
                            EuroStandard = "Euro 3",
                            FuelType = "Diesel",
                            Gearbox = "Automatic",
                            HorsePower = 121,
                            Make = "Brand21",
                            Mileage = 2100,
                            Model = "Model21",
                            Price = 210000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2021
                        },
                        new
                        {
                            Id = "c77987d5-0ec7-411f-8052-d2865d59fe42",
                            Axles = 8,
                            Color = "Black",
                            Condition = "Used",
                            CreatedOn = "8/11/2023 6:01:59 PM",
                            Description = "Description for Car 22",
                            EuroStandard = "Euro 4",
                            FuelType = "Gasoline",
                            Gearbox = "Automatic",
                            HorsePower = 122,
                            Make = "Brand22",
                            Mileage = 2200,
                            Model = "Model22",
                            Price = 220000m,
                            UserId = "824856e7-f56b-4f18-807f-d75e04c81ed0",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Tyre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOT")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Inches")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeedIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyreIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tyres");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Car", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Motorcycle", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Motorcycles")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Truck", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Trucks")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.Tyre", b =>
                {
                    b.HasOne("NeMobileBg.Data.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NeMobileBg.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Motorcycles");

                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
